# Generated by Django 4.2.6 on 2023-11-10 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebi', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=1, max_digits=7),
        ),
    ]
